services:
  - type: web
    name: uninav-backend
    env: node
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start:prod
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
