export const TABLES = {
  USERS: 'users',
  AUTH: 'auth',
  MODERATOR: 'moderator',
  FACULTY: 'faculty',
  DEPARTMENT: 'department',
  COURSES: 'courses',
  DEPARTMENT_LEVEL_COURSES: 'department_level_courses',
  USERS_COURSES: 'users_courses',
  STUDENT_COURSES: 'student_courses',
  MATERIALS: 'material',
  RESOURCE: 'resource',
  COLLECTION: 'collection',
  COLLECTION_MATERIAL: 'collection_material',
  BOOKMARKS: 'bookmarks',
  BLOGS: 'blogs',
  COMMENTS: 'comments',
  ADVERT: 'advert',
} as const;
