export enum ENV {
  NODE_ENV = 'NODE_ENV',
  DATABASE_URL = 'DATABASE_URL',
  DATABASE_URL_DEV = 'DATABASE_URL_DEV',
  PORT = 'PORT',
  JWT_SECRET = 'JWT_SECRET',
  BCRYPT_SALT_ROUNDS = 'BCRYPT_SALT_ROUNDS',
  BCRYPT_PEPPER = 'BCRYPT_PEPPER',

  B2_ACCESS_KEY = 'B2_ACCESS_KEY',
  B2_SECRET_KEY = 'B2_SECRET_KEY',
  B2_REGION = 'B2_REGION',
  B2_ENDPOINT = 'B2_ENDPOINT',

  GMAIL_CLIENT_ID = 'GMAIL_CLIENT_ID',
  GMAIL_CLIENT_SECRET = 'GMAIL_CLIENT_SECRET',

  GMAIL_REFRESH_TOKEN = 'GMAIL_REFRESH_TOKEN',
  COMPANY_EMAIL = 'COMPANY_EMAIL',
  COMPANY_NAME = 'COMPANY_NAME',

  CRYPTO_IV = 'CRYPTO_IV',
  CRYPTO_KEY = 'CRYPTO_KEY',
  CRYPTO_ENCRYPTION_ALGORITHM = 'CRYPTO_ENCRYPTION_ALGORITHM',
}
