export enum ENV {
  NODE_ENV = 'NODE_ENV',
  DATABASE_URL = 'DATABASE_URL',
  DATABASE_URL_DEV = 'DATABASE_URL_DEV',
  PORT = 'PORT',
  JWT_SECRET = 'JWT_SECRET',
  BCRYPT_SALT_ROUNDS = 'BCRYPT_SALT_ROUNDS',
  BCRYPT_PEPPER = 'BCRYPT_PEPPER',

  B2_ACCESS_KEY = 'B2_ACCESS_KEY',
  B2_SECRET_KEY = 'B2_SECRET_KEY',
  B2_REGION = 'B2_REGION',
  B2_ENDPOINT = 'B2_ENDPOINT',

  GMAIL_CLIENT_ID = 'GMAIL_CLIENT_ID',
  GMAIL_CLIENT_SECRET = 'GMAIL_CLIENT_SECRET',

  GMAIL_REFRESH_TOKEN = 'GMAIL_REFRESH_TOKEN',
  COMPANY_EMAIL = 'COMPANY_EMAIL',
  COMPANY_NAME = 'COMPANY_NAME',

  BREVO_API_KEY = 'BREVO_API_KEY',
  BREVO_SENDER_EMAIL = 'BREVO_SENDER_EMAIL',

  // MailSend
  MAILSEND_API_KEY = 'MAILSEND_API_KEY',
  MAILSEND_SENDER_EMAIL = 'MAILSEND_SENDER_EMAIL',

  // Resend
  RESEND_API_KEY = 'RESEND_API_KEY',
  RESEND_SENDER_EMAIL = 'RESEND_SENDER_EMAIL',

  CRYPTO_IV = 'CRYPTO_IV',
  CRYPTO_KEY = 'CRYPTO_KEY',
  CRYPTO_ENCRYPTION_ALGORITHM = 'CRYPTO_ENCRYPTION_ALGORITHM',

  FRONTEND_URL = 'FRONTEND_URL',
  ROOT_API_KEY = 'ROOT_API_KEY',

  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_REDIRECT_URI = 'GOOGLE_REDIRECT_URI',
}
