export enum EmailType {
  WELCOME = 'WELCOME',
  PASSWORD_RESET = 'PASSWORD_RESET',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  EMAIL_VERIFICATION_SUCCESS = 'EMAIL_VERIFICATION_SUCCESS',
  CONTACT_US = 'CONTACT_US',
  MATERIAL_REJECTION = 'MATERIAL_REJECTION',
  BLOG_REJECTION = 'BLOG_REJECTION',
  MODERATOR_REJECTION = 'MODERATOR_REJECTION',
  COURSE_REJECTION = 'COURSE_REJECTION',
  DLC_REJECTION = 'DLC_REJECTION',
  ADVERT_REJECTION = 'ADVERT_REJECTION',
}
