export const TABLES = {
  USERS: 'users',
  AUTH: 'auth',
  MODERATOR: 'moderator',
  FACULTY: 'faculty',
  DEPARTMENT: 'department',
  COURSES: 'courses',
  DEPARTMENT_LEVEL_COURSES: 'department_level_courses',
  USERS_COURSES: 'users_courses',
  STUDENT_COURSES: 'student_courses',
  MATERIALS: 'material',
  RESOURCE: 'resource',
  COLLECTION: 'collection',
  COLLECTION_CONTENT: 'collection_content',
  BOOKMARKS: 'bookmarks',
  BLOGS: 'blogs',
  COMMENTS: 'comments',
  ADVERT: 'advert',
  BLOG_LIKES: 'blog_likes',
  MATERIAL_LIKES: 'material_likes',
  RECENT: 'recent',
  ADMIN: 'admin',
  POINTS: 'points',
  NOTIFICATIONS: 'notifications',
  ERROR_REPORTS: 'error_reports',
  READING_PROGRESS: 'reading_progress',
} as const;
