export const TABLES = {
  USERS: 'users',
  AUTH: 'auth',
  MODERATOR: 'moderator',
  FACULTY: 'faculty',
  DEPARTMENT: 'department',
  COURSES: 'courses',
  DEPARTMENT_LEVEL_COURSES: 'department_level_courses',
  USERS_COURSES: 'users_courses',
  STUDENT_COURSES: 'student_courses',
  MATERIALS: 'material',
  RESOURCE: 'resource',
  COLLECTION: 'collection',
  COLLECTION_CONTENT: 'collection_content',
  BOOKMARKS: 'bookmarks',
  BLOGS: 'blogs',
  COMMENTS: 'comments',
  ADVERT: 'advert',
  BLOG_LIKES: 'blog_likes',
  MATERIAL_LIKES: 'material_likes',
  RECENT: 'recent',
  ADMIN: 'admin',
  CLUBS: 'clubs',
  CLUB_TARGET_DEPARTMENTS: 'club_target_departments',
  CLUB_CLICKS: 'club_clicks',
  CLUB_FLAGS: 'club_flags',
  CLUB_REQUESTS: 'club_requests',
} as const;
